version: '3'
services:
  nginx:
    build:
        context: .
        dockerfile: ./requirements/nginx/Dockerfile
          #volumes:
          #- nginx:/etc/nginx/conf.d
          #- /data/html:/var/www/html
    ports:
      - 80:80
        #links:
        #- wordpress
